# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Leetmock < Formula
  desc "A CLI tool for mocking LeetCode data"
  homepage "https://github.com/go-johnnyhe/leetmock"
  version "0.1.19"

  on_macos do
    on_intel do
      url "https://github.com/go-johnnyhe/leetmock/releases/download/v0.1.19/leetmock_0.1.19_darwin_amd64.tar.gz"
      sha256 "68f790689eb953f5123d46fa79ce8124ddc02659f5968130980c13d8476e24fa"

      def install
        bin.install "leetmock"
      end
    end
    on_arm do
      url "https://github.com/go-johnnyhe/leetmock/releases/download/v0.1.19/leetmock_0.1.19_darwin_arm64.tar.gz"
      sha256 "7901a250306c3dfd2bd5726da035fdfd52feefb8d819d40153e9ef6697efd7ca"

      def install
        bin.install "leetmock"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/go-johnnyhe/leetmock/releases/download/v0.1.19/leetmock_0.1.19_linux_amd64.tar.gz"
        sha256 "ac36be0c4739ae8e849174f7edb04af5fa11cffaebcfe9acdcd77c6ef6d0046a"

        def install
          bin.install "leetmock"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/go-johnnyhe/leetmock/releases/download/v0.1.19/leetmock_0.1.19_linux_arm64.tar.gz"
        sha256 "55911c0ae848aed1579fdc7f11db6c8ebb6fa087b17ac66a148138e9582d3c82"

        def install
          bin.install "leetmock"
        end
      end
    end
  end
end
