# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Leetmock < Formula
  desc "A CLI tool for mocking LeetCode data"
  homepage "https://github.com/go-johnnyhe/leetmock"
  version "0.1.18"

  on_macos do
    on_intel do
      url "https://github.com/go-johnnyhe/leetmock/releases/download/v0.1.18/leetmock_0.1.18_darwin_amd64.tar.gz"
      sha256 "43b2dd6cdc59ea6630000c7d56639e0740a077ef34252c909a1cacffe307100c"

      def install
        bin.install "leetmock"
      end
    end
    on_arm do
      url "https://github.com/go-johnnyhe/leetmock/releases/download/v0.1.18/leetmock_0.1.18_darwin_arm64.tar.gz"
      sha256 "6506d319beb266f65a26d206c34cfdcaadbf7c33f9684ffba4d3288d5f332a7a"

      def install
        bin.install "leetmock"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/go-johnnyhe/leetmock/releases/download/v0.1.18/leetmock_0.1.18_linux_amd64.tar.gz"
        sha256 "5d9c3cf38117890e370f3b3ec1f088eac1e7b78370a2c5e920b5753d6627f237"

        def install
          bin.install "leetmock"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/go-johnnyhe/leetmock/releases/download/v0.1.18/leetmock_0.1.18_linux_arm64.tar.gz"
        sha256 "64593d24cd59edd1164fb73b8d0e3cf88b3b2ab91cddf34d10199aa4558e431e"

        def install
          bin.install "leetmock"
        end
      end
    end
  end
end
