# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Leetmock < Formula
  desc "A CLI tool for mocking LeetCode data"
  homepage "https://github.com/go-johnnyhe/leetmock"
  version "0.1.22"

  on_macos do
    on_intel do
      url "https://github.com/go-johnnyhe/leetmock/releases/download/v0.1.22/leetmock_0.1.22_darwin_amd64.tar.gz"
      sha256 "aec78a1489b697842ac05373f5111d57bc6a469c5143de19d115cc2e4e952972"

      def install
        bin.install "leetmock"
      end
    end
    on_arm do
      url "https://github.com/go-johnnyhe/leetmock/releases/download/v0.1.22/leetmock_0.1.22_darwin_arm64.tar.gz"
      sha256 "319c96f5cd08c96d13caa13f871be2f82c7d69f41cd20faf473a6ea6914931f5"

      def install
        bin.install "leetmock"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/go-johnnyhe/leetmock/releases/download/v0.1.22/leetmock_0.1.22_linux_amd64.tar.gz"
        sha256 "b04ecbc490e62495d007bfbace4bfa5698d5a2ba956a975c22b07b36bbe6eac5"

        def install
          bin.install "leetmock"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/go-johnnyhe/leetmock/releases/download/v0.1.22/leetmock_0.1.22_linux_arm64.tar.gz"
        sha256 "6afd13ee29a9cf76cab2b069279b653426c28f2a64d6aa3446ba7693bdf204e6"

        def install
          bin.install "leetmock"
        end
      end
    end
  end
end
