# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shadow < Formula
  desc "A CLI tool collab coding"
  homepage "https://github.com/go-johnnyhe/shadow"
  version "0.2.01"

  on_macos do
    on_intel do
      url "https://github.com/go-johnnyhe/shadow/releases/download/v0.2.01/shadow_0.2.01_darwin_amd64.tar.gz"
      sha256 "ea93878e1d0945400960ec210946ec3a53dc5dab473ee40290cace95a74a5cf6"

      def install
        bin.install "shadow"
      end
    end
    on_arm do
      url "https://github.com/go-johnnyhe/shadow/releases/download/v0.2.01/shadow_0.2.01_darwin_arm64.tar.gz"
      sha256 "967b3d61a19e777355dbd00b809a2d4c7ae57b1a86effe08932d587115204b84"

      def install
        bin.install "shadow"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/go-johnnyhe/shadow/releases/download/v0.2.01/shadow_0.2.01_linux_amd64.tar.gz"
        sha256 "5b4a3e34c68ddfa62f5e93a52672add1efb92288bdc54f82de62f356fce5f857"

        def install
          bin.install "shadow"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/go-johnnyhe/shadow/releases/download/v0.2.01/shadow_0.2.01_linux_arm64.tar.gz"
        sha256 "9ddaf4a01d45f690d1b72286509b15076b7f3cb3ae61029896c10d1cd0bee1c6"

        def install
          bin.install "shadow"
        end
      end
    end
  end
end
