# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Waveland < Formula
  desc "A CLI tool for mocking LeetCode data"
  homepage "https://github.com/go-johnnyhe/waveland"
  version "0.1.24"

  on_macos do
    on_intel do
      url "https://github.com/go-johnnyhe/waveland/releases/download/v0.1.24/waveland_0.1.24_darwin_amd64.tar.gz"
      sha256 "e1c95d5cbbbc9a5abf49bdc7d4cbaa7c9080ee689bf2bb6ab97d5fac95a742b6"

      def install
        bin.install "waveland"
      end
    end
    on_arm do
      url "https://github.com/go-johnnyhe/waveland/releases/download/v0.1.24/waveland_0.1.24_darwin_arm64.tar.gz"
      sha256 "f2ae9965d109e9d1b3e25258b1a0164ff55296380a296e10a1cd2308809ebab9"

      def install
        bin.install "waveland"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/go-johnnyhe/waveland/releases/download/v0.1.24/waveland_0.1.24_linux_amd64.tar.gz"
        sha256 "32902a394da05e798a997ea9aa3c62e480e9d9952e1e3e35bad6f9608eafbbcd"

        def install
          bin.install "waveland"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/go-johnnyhe/waveland/releases/download/v0.1.24/waveland_0.1.24_linux_arm64.tar.gz"
        sha256 "37a9cba2360b163ca3915f16fb35a989fe6ed73af335bc54d6a6b08cf8e5c070"

        def install
          bin.install "waveland"
        end
      end
    end
  end
end
