# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Waveland < Formula
  desc "A CLI tool for mocking LeetCode data"
  homepage "https://github.com/go-johnnyhe/waveland"
  version "0.1.26"

  on_macos do
    on_intel do
      url "https://github.com/go-johnnyhe/waveland/releases/download/v0.1.26/waveland_0.1.26_darwin_amd64.tar.gz"
      sha256 "41cf18b29762bdfb97ced43ff295396c64d8cc516cffa44172254329f4337ff0"

      def install
        bin.install "waveland"
      end
    end
    on_arm do
      url "https://github.com/go-johnnyhe/waveland/releases/download/v0.1.26/waveland_0.1.26_darwin_arm64.tar.gz"
      sha256 "5ff854456b5d98051eeb43fd2f99990096ff6f6e133bccef4cb325880c901737"

      def install
        bin.install "waveland"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/go-johnnyhe/waveland/releases/download/v0.1.26/waveland_0.1.26_linux_amd64.tar.gz"
        sha256 "f6a272ded1e8f6372b8f37055038d472564420aa7e013fbec8621e6a4f6a8f0c"

        def install
          bin.install "waveland"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/go-johnnyhe/waveland/releases/download/v0.1.26/waveland_0.1.26_linux_arm64.tar.gz"
        sha256 "db6da5409cf677f462ace89bfdd48ac70549feba3d705689e49f6ff5cfb1e24c"

        def install
          bin.install "waveland"
        end
      end
    end
  end
end
