# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Waveland < Formula
  desc "A CLI tool for mocking LeetCode data"
  homepage "https://github.com/go-johnnyhe/waveland"
  version "0.1.25"

  on_macos do
    on_intel do
      url "https://github.com/go-johnnyhe/waveland/releases/download/v0.1.25/waveland_0.1.25_darwin_amd64.tar.gz"
      sha256 "ac23b8d23f00ab42e1e867f68cddb409d5cf509da6a2df4adb9367785b0f65ea"

      def install
        bin.install "waveland"
      end
    end
    on_arm do
      url "https://github.com/go-johnnyhe/waveland/releases/download/v0.1.25/waveland_0.1.25_darwin_arm64.tar.gz"
      sha256 "2600e97f1704b8630efc8c1bd32c620f5f8fce681e552a2fb2b67c7b7ffacfea"

      def install
        bin.install "waveland"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/go-johnnyhe/waveland/releases/download/v0.1.25/waveland_0.1.25_linux_amd64.tar.gz"
        sha256 "24579dbfeb2509534eeb476e6f24a62486d0afa6a84eaf72f6ac886639e38085"

        def install
          bin.install "waveland"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/go-johnnyhe/waveland/releases/download/v0.1.25/waveland_0.1.25_linux_arm64.tar.gz"
        sha256 "35645ce3c860738a43f6b5153fa4b83f44b96f08fbcd813a80a2ce1694fe3c87"

        def install
          bin.install "waveland"
        end
      end
    end
  end
end
